DEFAULT_SERVICE_NAME = "test"
DEFAULT_ENV_NAME = "none"
DEFAULT_SITE = "datadoghq.com"

DEFAULT_AGENT_HOSTNAME = "localhost"
DEFAULT_AGENT_PORT = 8126

TAG_TRUE = "true"
TAG_FALSE = "false"

EMPTY_NAME = "."
